version: '3.4'

services:
  mongodatabase:
    container_name: sira-mongo-dev
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks: 
      - sira-mongo-compose-network
    ports:
      - '27017:27017'
    volumes: 
      - ./MongoData:/data/db
  
  mongo-express:
    container_name: sira-mongo-express
    image: mongo-express
    depends_on:
      - mongodatabase
    networks: 
      - sira-mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodatabase
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    restart: unless-stopped
    ports:
      - '8081:8081'
    volumes: 
      - ./MongoData:/data/db  
networks:
  sira-mongo-compose-network:
    driver: bridge      
